# rules for mesa 17.3.9

MESA_DIST_VERSION=17.3.9

MesaUtilLib_SRC  = \
	$(MESA_VER)/src/util/bitscan.c \
	$(MESA_VER)/src/util/build_id.c \
	$(MESA_VER)/src/util/crc32.c \
	$(MESA_VER)/src/util/debug.c \
	$(MESA_VER)/src/util/disk_cache.c \
	$(MESA_VER)/src/util/half_float.c \
	$(MESA_VER)/src/util/hash_table.c \
	$(MESA_VER)/src/util/ralloc.c \
	$(MESA_VER)/src/util/rand_xor.c \
	$(MESA_VER)/src/util/register_allocate.c \
	$(MESA_VER)/src/util/rgtc.c \
	$(MESA_VER)/src/util/set.c \
	$(MESA_VER)/src/util/mesa-sha1.c \
	$(MESA_VER)/src/util/sha1/sha1.c \
	$(MESA_VER)/src/util/slab.c \
	$(MESA_VER)/src/util/string_buffer.c \
	$(MESA_VER)/src/util/strtod.c \
	$(MESA_VER)/src/util/u_atomic.c \
	$(MESA_VER)/src/util/u_queue.c \
	$(MESA_VER)/src/util/u_vector.c
# Auto-generated
MesaUtilLib_SRC += \
	$(MESA_VER)/src/util/format_srgb.c

MesaLib_SRC  = \
	$(MESA_VER)/src/mesa/state_tracker/st_atifs_to_tgsi.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_array.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_atomicbuf.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_blend.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_clip.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_constbuf.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_depth.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_framebuffer.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_image.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_msaa.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_pixeltransfer.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_rasterizer.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_sampler.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_scissor.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_shader.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_stipple.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_storagebuf.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_tess.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_texture.c \
	$(MESA_VER)/src/mesa/state_tracker/st_atom_viewport.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_bitmap.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_bitmap_shader.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_blit.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_bufferobjects.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_clear.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_compute.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_condrender.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_copyimage.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_drawpixels.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_drawpixels_shader.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_drawtex.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_eglimage.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_fbo.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_feedback.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_flush.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_memoryobjects.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_msaa.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_perfmon.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_program.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_queryobj.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_rasterpos.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_readpixels.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_strings.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_syncobj.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_texturebarrier.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_texture.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_viewport.c \
	$(MESA_VER)/src/mesa/state_tracker/st_cb_xformfb.c \
	$(MESA_VER)/src/mesa/state_tracker/st_context.c \
	$(MESA_VER)/src/mesa/state_tracker/st_copytex.c \
	$(MESA_VER)/src/mesa/state_tracker/st_debug.c \
	$(MESA_VER)/src/mesa/state_tracker/st_draw.c \
	$(MESA_VER)/src/mesa/state_tracker/st_draw_feedback.c \
	$(MESA_VER)/src/mesa/state_tracker/st_extensions.c \
	$(MESA_VER)/src/mesa/state_tracker/st_format.c \
	$(MESA_VER)/src/mesa/state_tracker/st_gen_mipmap.c \
	$(MESA_VER)/src/mesa/state_tracker/st_glsl_to_nir.cpp \
	$(MESA_VER)/src/mesa/state_tracker/st_glsl_to_tgsi.cpp \
	$(MESA_VER)/src/mesa/state_tracker/st_glsl_to_tgsi_private.cpp \
	$(MESA_VER)/src/mesa/state_tracker/st_glsl_to_tgsi_temprename.cpp \
	$(MESA_VER)/src/mesa/state_tracker/st_glsl_types.cpp \
	$(MESA_VER)/src/mesa/state_tracker/st_manager.c \
	$(MESA_VER)/src/mesa/state_tracker/st_mesa_to_tgsi.c \
	$(MESA_VER)/src/mesa/state_tracker/st_nir_lower_builtin.c \
	$(MESA_VER)/src/mesa/state_tracker/st_nir_lower_tex_src_plane.c \
	$(MESA_VER)/src/mesa/state_tracker/st_pbo.c \
	$(MESA_VER)/src/mesa/state_tracker/st_program.c \
	$(MESA_VER)/src/mesa/state_tracker/st_sampler_view.c \
	$(MESA_VER)/src/mesa/state_tracker/st_scissor.c \
	$(MESA_VER)/src/mesa/state_tracker/st_shader_cache.c \
	$(MESA_VER)/src/mesa/state_tracker/st_texture.c \
	$(MESA_VER)/src/mesa/state_tracker/st_tgsi_lower_yuv.c \
	$(MESA_VER)/src/mesa/state_tracker/st_vdpau.c
MesaLib_SRC += \
	$(MESA_VER)/src/mesa/program/arbprogparse.c \
	$(MESA_VER)/src/mesa/program/ir_to_mesa.cpp \
	$(MESA_VER)/src/mesa/program/lex.yy.c \
	$(MESA_VER)/src/mesa/program/prog_cache.c \
	$(MESA_VER)/src/mesa/program/prog_execute.c \
	$(MESA_VER)/src/mesa/program/prog_instruction.c \
	$(MESA_VER)/src/mesa/program/prog_noise.c \
	$(MESA_VER)/src/mesa/program/prog_opt_constant_fold.c \
	$(MESA_VER)/src/mesa/program/prog_optimize.c \
	$(MESA_VER)/src/mesa/program/prog_parameter.c \
	$(MESA_VER)/src/mesa/program/prog_parameter_layout.c \
	$(MESA_VER)/src/mesa/program/prog_print.c \
	$(MESA_VER)/src/mesa/program/program.c \
	$(MESA_VER)/src/mesa/program/programopt.c \
	$(MESA_VER)/src/mesa/program/program_parse_extra.c \
	$(MESA_VER)/src/mesa/program/program_parse.tab.c \
	$(MESA_VER)/src/mesa/program/prog_statevars.c \
	$(MESA_VER)/src/mesa/program/symbol_table.c
MesaLib_SRC += \
	$(MESA_VER)/src/mesa/main/accum.c \
	$(MESA_VER)/src/mesa/main/api_arrayelt.c \
	$(MESA_VER)/src/mesa/main/api_exec.c \
	$(MESA_VER)/src/mesa/main/api_loopback.c \
	$(MESA_VER)/src/mesa/main/api_validate.c \
	$(MESA_VER)/src/mesa/main/arbprogram.c \
	$(MESA_VER)/src/mesa/main/arrayobj.c \
	$(MESA_VER)/src/mesa/main/atifragshader.c \
	$(MESA_VER)/src/mesa/main/attrib.c \
	$(MESA_VER)/src/mesa/main/barrier.c \
	$(MESA_VER)/src/mesa/main/bbox.c \
	$(MESA_VER)/src/mesa/main/blend.c \
	$(MESA_VER)/src/mesa/main/blit.c \
	$(MESA_VER)/src/mesa/main/bufferobj.c \
	$(MESA_VER)/src/mesa/main/buffers.c \
	$(MESA_VER)/src/mesa/main/clear.c \
	$(MESA_VER)/src/mesa/main/clip.c \
	$(MESA_VER)/src/mesa/main/colortab.c \
	$(MESA_VER)/src/mesa/main/compute.c \
	$(MESA_VER)/src/mesa/main/condrender.c \
	$(MESA_VER)/src/mesa/main/context.c \
	$(MESA_VER)/src/mesa/main/convolve.c \
	$(MESA_VER)/src/mesa/main/copyimage.c \
	$(MESA_VER)/src/mesa/main/cpuinfo.c \
	$(MESA_VER)/src/mesa/main/debug.c \
	$(MESA_VER)/src/mesa/main/debug_output.c \
	$(MESA_VER)/src/mesa/main/depth.c \
	$(MESA_VER)/src/mesa/main/dlist.c \
	$(MESA_VER)/src/mesa/main/drawpix.c \
	$(MESA_VER)/src/mesa/main/drawtex.c \
	$(MESA_VER)/src/mesa/main/enable.c \
	$(MESA_VER)/src/mesa/main/enums.c \
	$(MESA_VER)/src/mesa/main/errors.c \
	$(MESA_VER)/src/mesa/main/eval.c \
	$(MESA_VER)/src/mesa/main/execmem.c \
	$(MESA_VER)/src/mesa/main/extensions.c \
	$(MESA_VER)/src/mesa/main/extensions_table.c \
	$(MESA_VER)/src/mesa/main/externalobjects.c \
	$(MESA_VER)/src/mesa/main/fbobject.c \
	$(MESA_VER)/src/mesa/main/feedback.c \
	$(MESA_VER)/src/mesa/main/ff_fragment_shader.cpp \
	$(MESA_VER)/src/mesa/main/ffvertex_prog.c \
	$(MESA_VER)/src/mesa/main/fog.c \
	$(MESA_VER)/src/mesa/main/format_fallback.c \
	$(MESA_VER)/src/mesa/main/format_pack.c \
	$(MESA_VER)/src/mesa/main/format_unpack.c \
	$(MESA_VER)/src/mesa/main/formatquery.c \
	$(MESA_VER)/src/mesa/main/formats.c \
	$(MESA_VER)/src/mesa/main/format_utils.c \
	$(MESA_VER)/src/mesa/main/framebuffer.c \
	$(MESA_VER)/src/mesa/main/get.c \
	$(MESA_VER)/src/mesa/main/genmipmap.c \
	$(MESA_VER)/src/mesa/main/getstring.c \
	$(MESA_VER)/src/mesa/main/glformats.c \
	$(MESA_VER)/src/mesa/main/glthread.c \
	$(MESA_VER)/src/mesa/main/hash.c \
	$(MESA_VER)/src/mesa/main/hint.c \
	$(MESA_VER)/src/mesa/main/histogram.c \
	$(MESA_VER)/src/mesa/main/image.c \
	$(MESA_VER)/src/mesa/main/imports.c \
	$(MESA_VER)/src/mesa/main/light.c \
	$(MESA_VER)/src/mesa/main/lines.c \
	$(MESA_VER)/src/mesa/main/marshal.c \
	$(MESA_VER)/src/mesa/main/marshal_generated.c \
	$(MESA_VER)/src/mesa/main/matrix.c \
	$(MESA_VER)/src/mesa/main/mipmap.c \
	$(MESA_VER)/src/mesa/main/mm.c \
	$(MESA_VER)/src/mesa/main/multisample.c \
	$(MESA_VER)/src/mesa/main/objectlabel.c \
	$(MESA_VER)/src/mesa/main/objectpurge.c \
	$(MESA_VER)/src/mesa/main/pack.c \
	$(MESA_VER)/src/mesa/main/pbo.c \
	$(MESA_VER)/src/mesa/main/performance_monitor.c \
	$(MESA_VER)/src/mesa/main/performance_query.c \
	$(MESA_VER)/src/mesa/main/pipelineobj.c \
	$(MESA_VER)/src/mesa/main/pixel.c \
	$(MESA_VER)/src/mesa/main/pixelstore.c \
	$(MESA_VER)/src/mesa/main/pixeltransfer.c \
	$(MESA_VER)/src/mesa/main/points.c \
	$(MESA_VER)/src/mesa/main/polygon.c \
	$(MESA_VER)/src/mesa/main/program_resource.c \
	$(MESA_VER)/src/mesa/main/querymatrix.c \
	$(MESA_VER)/src/mesa/main/queryobj.c \
	$(MESA_VER)/src/mesa/main/rastpos.c \
	$(MESA_VER)/src/mesa/main/readpix.c \
	$(MESA_VER)/src/mesa/main/remap.c \
	$(MESA_VER)/src/mesa/main/renderbuffer.c \
	$(MESA_VER)/src/mesa/main/robustness.c \
	$(MESA_VER)/src/mesa/main/samplerobj.c \
	$(MESA_VER)/src/mesa/main/scissor.c \
	$(MESA_VER)/src/mesa/main/shaderapi.c \
	$(MESA_VER)/src/mesa/main/shaderimage.c \
	$(MESA_VER)/src/mesa/main/shaderobj.c \
	$(MESA_VER)/src/mesa/main/shader_query.cpp \
	$(MESA_VER)/src/mesa/main/shared.c \
	$(MESA_VER)/src/mesa/main/state.c \
	$(MESA_VER)/src/mesa/main/stencil.c \
	$(MESA_VER)/src/mesa/main/syncobj.c \
	$(MESA_VER)/src/mesa/main/texcompress.c \
	$(MESA_VER)/src/mesa/main/texcompress_bptc.c \
	$(MESA_VER)/src/mesa/main/texcompress_cpal.c \
	$(MESA_VER)/src/mesa/main/texcompress_etc.c \
	$(MESA_VER)/src/mesa/main/texcompress_fxt1.c \
	$(MESA_VER)/src/mesa/main/texcompress_rgtc.c \
	$(MESA_VER)/src/mesa/main/texcompress_s3tc.c \
	$(MESA_VER)/src/mesa/main/texenv.c \
	$(MESA_VER)/src/mesa/main/texformat.c \
	$(MESA_VER)/src/mesa/main/texgen.c \
	$(MESA_VER)/src/mesa/main/texgetimage.c \
	$(MESA_VER)/src/mesa/main/teximage.c \
	$(MESA_VER)/src/mesa/main/texobj.c \
	$(MESA_VER)/src/mesa/main/texparam.c \
	$(MESA_VER)/src/mesa/main/texstate.c \
	$(MESA_VER)/src/mesa/main/texstorage.c \
	$(MESA_VER)/src/mesa/main/texstore.c \
	$(MESA_VER)/src/mesa/main/texturebindless.c \
	$(MESA_VER)/src/mesa/main/textureview.c \
	$(MESA_VER)/src/mesa/main/transformfeedback.c \
	$(MESA_VER)/src/mesa/main/uniform_query.cpp \
	$(MESA_VER)/src/mesa/main/uniforms.c \
	$(MESA_VER)/src/mesa/main/varray.c \
	$(MESA_VER)/src/mesa/main/vdpau.c \
	$(MESA_VER)/src/mesa/main/version.c \
	$(MESA_VER)/src/mesa/main/viewport.c \
	$(MESA_VER)/src/mesa/main/vtxfmt.c \
	$(MESA_VER)/src/mesa/main/es1_conversion.c
MesaLib_SRC += \
	$(MESA_VER)/src/mesa/math/m_debug_clip.c \
	$(MESA_VER)/src/mesa/math/m_debug_norm.c \
	$(MESA_VER)/src/mesa/math/m_debug_xform.c \
	$(MESA_VER)/src/mesa/math/m_eval.c \
	$(MESA_VER)/src/mesa/math/m_matrix.c \
	$(MESA_VER)/src/mesa/math/m_translate.c \
	$(MESA_VER)/src/mesa/math/m_vector.c
MesaLib_SRC += \
	$(MESA_VER)/src/mesa/vbo/vbo_context.c \
	$(MESA_VER)/src/mesa/vbo/vbo_exec_api.c \
	$(MESA_VER)/src/mesa/vbo/vbo_exec_array.c \
	$(MESA_VER)/src/mesa/vbo/vbo_exec.c \
	$(MESA_VER)/src/mesa/vbo/vbo_exec_draw.c \
	$(MESA_VER)/src/mesa/vbo/vbo_exec_eval.c \
	$(MESA_VER)/src/mesa/vbo/vbo_minmax_index.c \
	$(MESA_VER)/src/mesa/vbo/vbo_noop.c \
	$(MESA_VER)/src/mesa/vbo/vbo_primitive_restart.c \
	$(MESA_VER)/src/mesa/vbo/vbo_rebase.c \
	$(MESA_VER)/src/mesa/vbo/vbo_save_api.c \
	$(MESA_VER)/src/mesa/vbo/vbo_save.c \
	$(MESA_VER)/src/mesa/vbo/vbo_save_draw.c \
	$(MESA_VER)/src/mesa/vbo/vbo_save_loopback.c \
	$(MESA_VER)/src/mesa/vbo/vbo_split.c \
	$(MESA_VER)/src/mesa/vbo/vbo_split_copy.c \
	$(MESA_VER)/src/mesa/vbo/vbo_split_inplace.c
MesaLib_SRC += \
	$(MESA_VER)/src/compiler/blob.c \
	$(MESA_VER)/src/compiler/glsl_types.cpp \
	$(MESA_VER)/src/compiler/nir_types.cpp \
	$(MESA_VER)/src/compiler/shader_enums.c \
	$(MESA_VER)/src/compiler/glsl/ast_array_index.cpp \
	$(MESA_VER)/src/compiler/glsl/ast_expr.cpp \
	$(MESA_VER)/src/compiler/glsl/ast_function.cpp \
	$(MESA_VER)/src/compiler/glsl/ast_to_hir.cpp \
	$(MESA_VER)/src/compiler/glsl/ast_type.cpp \
	$(MESA_VER)/src/compiler/glsl/builtin_functions.cpp \
	$(MESA_VER)/src/compiler/glsl/builtin_types.cpp \
	$(MESA_VER)/src/compiler/glsl/builtin_variables.cpp \
	$(MESA_VER)/src/compiler/glsl/generate_ir.cpp \
	$(MESA_VER)/src/compiler/glsl/glsl_parser_extras.cpp \
	$(MESA_VER)/src/compiler/glsl/glsl_symbol_table.cpp \
	$(MESA_VER)/src/compiler/glsl/glsl_to_nir.cpp \
	$(MESA_VER)/src/compiler/glsl/hir_field_selection.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_array_refcount.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_basic_block.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_builder.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_clone.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_constant_expression.cpp \
	$(MESA_VER)/src/compiler/glsl/ir.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_equals.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_expression_flattening.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_function_can_inline.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_function_detect_recursion.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_function.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_hierarchical_visitor.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_hv_accept.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_print_visitor.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_reader.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_rvalue_visitor.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_set_program_inouts.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_validate.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_variable_refcount.cpp \
	$(MESA_VER)/src/compiler/glsl/linker.cpp \
	$(MESA_VER)/src/compiler/glsl/link_atomics.cpp \
	$(MESA_VER)/src/compiler/glsl/link_functions.cpp \
	$(MESA_VER)/src/compiler/glsl/link_interface_blocks.cpp \
	$(MESA_VER)/src/compiler/glsl/link_uniforms.cpp \
	$(MESA_VER)/src/compiler/glsl/link_uniform_initializers.cpp \
	$(MESA_VER)/src/compiler/glsl/link_uniform_block_active_visitor.cpp \
	$(MESA_VER)/src/compiler/glsl/link_uniform_blocks.cpp \
	$(MESA_VER)/src/compiler/glsl/link_varyings.cpp \
	$(MESA_VER)/src/compiler/glsl/loop_analysis.cpp \
	$(MESA_VER)/src/compiler/glsl/loop_unroll.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_blend_equation_advanced.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_buffer_access.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_const_arrays_to_uniforms.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_cs_derived.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_discard.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_discard_flow.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_distance.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_if_to_cond_assign.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_instructions.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_int64.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_jumps.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_mat_op_to_vec.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_noise.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_offset_array.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_packed_varyings.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_named_interface_blocks.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_packing_builtins.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_subroutine.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_tess_level.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_texture_projection.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_variable_index_to_cond_assign.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vec_index_to_cond_assign.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vec_index_to_swizzle.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vector.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vector_derefs.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vector_insert.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_vertex_id.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_output_reads.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_shared_reference.cpp \
	$(MESA_VER)/src/compiler/glsl/lower_ubo_reference.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_algebraic.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_array_splitting.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_conditional_discard.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_constant_folding.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_constant_propagation.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_constant_variable.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_copy_propagation.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_copy_propagation_elements.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_dead_builtin_variables.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_dead_builtin_varyings.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_dead_code.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_dead_code_local.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_dead_functions.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_flatten_nested_if_blocks.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_flip_matrices.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_function_inlining.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_if_simplification.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_minmax.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_noop_swizzle.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_rebalance_tree.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_redundant_jumps.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_structure_splitting.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_swizzle_swizzle.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_tree_grafting.cpp \
	$(MESA_VER)/src/compiler/glsl/opt_vectorize.cpp \
	$(MESA_VER)/src/compiler/glsl/propagate_invariance.cpp \
	$(MESA_VER)/src/compiler/glsl/s_expression.cpp \
	$(MESA_VER)/src/compiler/glsl/string_to_uint_map.cpp \
	$(MESA_VER)/src/compiler/glsl/shader_cache.cpp \
	$(MESA_VER)/src/compiler/glsl/ir_builder_print_visitor.cpp \
	$(MESA_VER)/src/compiler/glsl/glsl_lexer.cpp \
	$(MESA_VER)/src/compiler/glsl/glsl_parser.cpp \
	$(MESA_VER)/src/compiler/glsl/glcpp/pp.c \
	$(MESA_VER)/src/compiler/glsl/glcpp/glcpp-lex.c \
	$(MESA_VER)/src/compiler/glsl/glcpp/glcpp-parse.c \
	$(MESA_VER)/src/compiler/nir/nir_constant_expressions.c \
	$(MESA_VER)/src/compiler/nir/nir_opcodes.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_algebraic.c \
	$(MESA_VER)/src/compiler/nir/nir.c \
	$(MESA_VER)/src/compiler/nir/nir_clone.c \
	$(MESA_VER)/src/compiler/nir/nir_control_flow.c \
	$(MESA_VER)/src/compiler/nir/nir_dominance.c \
	$(MESA_VER)/src/compiler/nir/nir_from_ssa.c \
	$(MESA_VER)/src/compiler/nir/nir_gather_info.c \
	$(MESA_VER)/src/compiler/nir/nir_gs_count_vertices.c \
	$(MESA_VER)/src/compiler/nir/nir_inline_functions.c \
	$(MESA_VER)/src/compiler/nir/nir_instr_set.c \
	$(MESA_VER)/src/compiler/nir/nir_intrinsics.c \
	$(MESA_VER)/src/compiler/nir/nir_linking_helpers.c \
	$(MESA_VER)/src/compiler/nir/nir_liveness.c \
	$(MESA_VER)/src/compiler/nir/nir_loop_analyze.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_64bit_packing.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_alpha_test.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_alu_to_scalar.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_atomics.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_atomics_to_ssbo.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_bitmap.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_clamp_color_outputs.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_clip.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_clip_cull_distance_arrays.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_constant_initializers.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_double_ops.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_drawpixels.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_global_vars_to_local.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_gs_intrinsics.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_load_const_to_scalar.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_locals_to_regs.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_idiv.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_indirect_derefs.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_int64.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_io.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_io_to_temporaries.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_io_to_scalar.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_io_types.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_passthrough_edgeflags.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_patch_vertices.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_phis_to_scalar.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_read_invocation_to_scalar.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_regs_to_ssa.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_returns.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_samplers.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_samplers_as_deref.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_system_values.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_tex.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_to_source_mods.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_two_sided_color.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_uniforms_to_ubo.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_vars_to_ssa.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_var_copies.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_vec_to_movs.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_wpos_center.c \
	$(MESA_VER)/src/compiler/nir/nir_lower_wpos_ytransform.c \
	$(MESA_VER)/src/compiler/nir/nir_metadata.c \
	$(MESA_VER)/src/compiler/nir/nir_move_vec_src_uses_to_dest.c \
	$(MESA_VER)/src/compiler/nir/nir_normalize_cubemap_coords.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_conditional_discard.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_constant_folding.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_copy_prop_vars.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_copy_propagate.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_cse.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_dce.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_dead_cf.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_gcm.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_global_to_local.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_if.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_intrinsics.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_loop_unroll.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_move_comparisons.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_peephole_select.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_remove_phis.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_trivial_continues.c \
	$(MESA_VER)/src/compiler/nir/nir_opt_undef.c \
	$(MESA_VER)/src/compiler/nir/nir_phi_builder.c \
	$(MESA_VER)/src/compiler/nir/nir_print.c \
	$(MESA_VER)/src/compiler/nir/nir_propagate_invariant.c \
	$(MESA_VER)/src/compiler/nir/nir_remove_dead_variables.c \
	$(MESA_VER)/src/compiler/nir/nir_repair_ssa.c \
	$(MESA_VER)/src/compiler/nir/nir_search.c \
	$(MESA_VER)/src/compiler/nir/nir_split_var_copies.c \
	$(MESA_VER)/src/compiler/nir/nir_sweep.c \
	$(MESA_VER)/src/compiler/nir/nir_to_lcssa.c \
	$(MESA_VER)/src/compiler/nir/nir_validate.c \
	$(MESA_VER)/src/compiler/nir/nir_worklist.c
MesaLib_SRC += \
	$(MESA_VER)/src/mapi/glapi/glapi_dispatch.c \
	$(MESA_VER)/src/mapi/glapi/glapi_entrypoint.c \
	$(MESA_VER)/src/mapi/glapi/glapi_getproc.c \
	$(MESA_VER)/src/mapi/glapi/glapi_nop.c \
	$(MESA_VER)/src/mapi/glapi/glapi.c \
	$(MESA_VER)/src/mapi/u_current.c \
	$(MESA_VER)/src/mapi/u_execmem.c
# Not used
#	$(MESA_VER)/src/compiler/glsl/standalone_scaffolding.cpp
#	$(MESA_VER)/src/compiler/glsl/standalone.cpp

MesaWglLib_SRC = \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_context.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_device.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_context.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_extensionsstring.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_pbuffer.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_pixelformat.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_rendertexture.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_ext_swapinterval.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_framebuffer.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_getprocaddress.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_nopfuncs.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_pixelformat.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_st.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_tls.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_wgl.c \
	$(MESA_VER)/src/gallium/state_trackers/wgl/stw_debug.c \
	extra/knownfolders.c \
	extra/clock_gettime32.c

MesaGalliumAuxLib_SRC = \
	$(MESA_VER)/src/gallium/auxiliary/cso_cache/cso_cache.c \
	$(MESA_VER)/src/gallium/auxiliary/cso_cache/cso_context.c \
	$(MESA_VER)/src/gallium/auxiliary/cso_cache/cso_hash.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_context.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_fs.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_gs.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_aaline.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_aapoint.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_clip.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_cull.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_flatshade.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_offset.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_pstipple.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_stipple.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_twoside.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_unfilled.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_util.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_validate.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_vbuf.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_wide_line.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pipe_wide_point.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_prim_assembler.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_emit.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_fetch.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_fetch_emit.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_fetch_shade_emit.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_fetch_shade_pipeline.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_post_vs.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_so_emit.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_util.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_vsplit.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_vertex.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_vs.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_vs_exec.c \
	$(MESA_VER)/src/gallium/auxiliary/draw/draw_vs_variant.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/font.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_context.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_cpu.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_nic.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_cpufreq.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_diskstat.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_sensors_temp.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_driver_query.c \
	$(MESA_VER)/src/gallium/auxiliary/hud/hud_fps.c \
	$(MESA_VER)/src/gallium/auxiliary/indices/u_primconvert.c \
	$(MESA_VER)/src/gallium/auxiliary/os/os_misc.c \
	$(MESA_VER)/src/gallium/auxiliary/os/os_process.c \
	$(MESA_VER)/src/gallium/auxiliary/os/os_time.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_buffer_fenced.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_buffer_malloc.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_alt.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_cache.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_debug.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_mm.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_ondemand.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_pool.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_bufmgr_slab.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_cache.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_slab.c \
	$(MESA_VER)/src/gallium/auxiliary/pipebuffer/pb_validate.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_celshade.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_colors.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_init.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_mlaa.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_program.c \
	$(MESA_VER)/src/gallium/auxiliary/postprocess/pp_run.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_connection.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_context.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_core.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_demarshal.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_shader.c \
	$(MESA_VER)/src/gallium/auxiliary/rbug/rbug_texture.c \
	$(MESA_VER)/src/gallium/auxiliary/rtasm/rtasm_cpu.c \
	$(MESA_VER)/src/gallium/auxiliary/rtasm/rtasm_execmem.c \
	$(MESA_VER)/src/gallium/auxiliary/rtasm/rtasm_x86sse.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_aa_point.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_build.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_dump.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_exec.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_emulate.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_from_mesa.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_info.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_iterate.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_lowering.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_parse.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_point_sprite.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_sanity.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_scan.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_strings.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_text.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_transform.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_two_side.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_ureg.c \
	$(MESA_VER)/src/gallium/auxiliary/tgsi/tgsi_util.c \
	$(MESA_VER)/src/gallium/auxiliary/translate/translate.c \
	$(MESA_VER)/src/gallium/auxiliary/translate/translate_cache.c \
	$(MESA_VER)/src/gallium/auxiliary/translate/translate_generic.c \
	$(MESA_VER)/src/gallium/auxiliary/translate/translate_sse.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_bitmask.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_blit.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_blitter.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_cache.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_cpu_detect.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_describe.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_flush.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_image.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_memory.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_refcnt.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_stack.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_debug_symbol.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_dl.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_draw.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_draw_quad.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_dump_defines.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_dump_state.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_etc.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_latc.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_other.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_rgtc.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_s3tc.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_tests.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_yuv.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_zs.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_framebuffer.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_gen_mipmap.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_handle_table.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_hash_table.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_helpers.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_index_modify.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_linear.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_math.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_mm.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_network.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_prim_restart.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_pstipple.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_resource.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_ringbuffer.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_sampler.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_simple_shaders.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_suballoc.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_surface.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_surfaces.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_tests.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_texture.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_tile.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_transfer.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_upload_mgr.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_vbuf.c
# Auto-generated
MesaGalliumAuxLib_SRC += \
	$(MESA_VER)/src/gallium/auxiliary/indices/u_indices_gen.c \
	$(MESA_VER)/src/gallium/auxiliary/indices/u_unfilled_gen.c \
	$(MESA_VER)/src/gallium/auxiliary/util/u_format_table.c

MesaGalliumAuxLibSimd_SRC = \
  $(MesaGalliumAuxLib_SRC) \
  $(MESA_VER)/src/gallium/auxiliary/draw/draw_llvm.c \
  $(MESA_VER)/src/gallium/auxiliary/draw/draw_llvm_sample.c \
  $(MESA_VER)/src/gallium/auxiliary/draw/draw_pt_fetch_shade_pipeline_llvm.c \
  $(MESA_VER)/src/gallium/auxiliary/draw/draw_vs_llvm.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_arit.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_arit_overflow.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_assert.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_bitarit.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_const.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_conv.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_flow.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_aos.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_aos_array.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_cached.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_float.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_soa.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_srgb.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_format_yuv.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_gather.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_init.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_intr.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_logic.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_pack.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_printf.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_quad.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_sample.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_sample_aos.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_sample_soa.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_struct.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_swizzle.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_tgsi.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_tgsi_action.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_tgsi_aos.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_tgsi_info.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_tgsi_soa.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_type.c \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_debug.cpp \
  $(MESA_VER)/src/gallium/auxiliary/gallivm/lp_bld_misc.cpp

MesaNineLib_SRC    = \
	$(MESA_VER)/src/gallium/state_trackers/nine/adapter9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/authenticatedchannel9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/basetexture9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/buffer9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/cryptosession9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/cubetexture9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/device9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/device9ex.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/device9video.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/guid.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/indexbuffer9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/iunknown.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_buffer_upload.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_debug.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_dump.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nineexoverlayextension.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_ff.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_helpers.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_lock.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_pipe.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_quirk.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_queue.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_shader.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/nine_state.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/pixelshader9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/query9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/resource9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/stateblock9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/surface9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/swapchain9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/swapchain9ex.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/texture9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/threadpool.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/vertexbuffer9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/vertexdeclaration9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/vertexshader9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/volume9.c \
	$(MESA_VER)/src/gallium/state_trackers/nine/volumetexture9.c

MesaSVGALib_SRC  = \
	$(MESA_VER)/src/gallium/drivers/svga/svga_cmd.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_cmd_vgpu10.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_context.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_draw_arrays.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_draw.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_draw_elements.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_format.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_link.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_msg.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_blend.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_blit.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_clear.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_constants.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_depthstencil.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_draw.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_flush.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_fs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_gs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_misc.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_query.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_rasterizer.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_sampler.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_streamout.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_vertex.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_pipe_vs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_resource_buffer.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_resource_buffer_upload.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_resource.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_resource_texture.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_sampler_view.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_screen.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_screen_cache.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_shader.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_constants.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_framebuffer.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_fs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_gs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_need_swtnl.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_rss.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_sampler.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_tgsi_transform.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_tss.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_vdecl.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_state_vs.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_surface.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_swtnl_backend.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_swtnl_draw.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_swtnl_state.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_tgsi.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_tgsi_decl_sm30.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_tgsi_insn.c \
	$(MESA_VER)/src/gallium/drivers/svga/svga_tgsi_vgpu10.c \
	$(MESA_VER)/src/gallium/drivers/svga/svgadump/svga_dump.c \
	$(MESA_VER)/src/gallium/drivers/svga/svgadump/svga_shader_dump.c \
	$(MESA_VER)/src/gallium/drivers/svga/svgadump/svga_shader_op.c

MesaSVGAWinsysLib_SRC  = \
	$(MESA_VER)/src/gallium/winsys/svga/drm/pb_buffer_simple_fenced.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_buffer.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_context.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_fence.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_screen_pools.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_screen_svga.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_surface.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_shader.c \
	$(MESA_VER)/src/gallium/winsys/svga/drm/vmw_query.c \
	win9x/winsys/vmw_screen.c \
	win9x/winsys/vmw_screen_ioctl.c \
	win9x/winsys/vmw_screen_wddm.c \
	win9x/gadrv9x.cpp \
	win9x/gadrv9xenv.cpp \
	win9x/svgadrv.c
	
MesaGalliumSWRLib_SRC = \
	$(MESA_VER)/src/gallium/drivers/swr/swr_loader.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_clear.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_context.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_draw.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_screen.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_state.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_tex_sample.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_scratch.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_shader.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_fence.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_fence_work.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/swr_query.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/archrast/archrast.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/common/formats.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/common/os.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/common/rdtsc_buckets.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/common/swr_assert.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/api.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/backend.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/backend_clear.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/backend_sample.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/backend_singlesample.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/binner.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/clip.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/frontend.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/pa_avx.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/rasterizer.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/rdtsc_core.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/threads.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/core/tilemgr.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/blend_jit.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/builder.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/builder_misc.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/fetch_jit.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/JitManager.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/jitter/streamout_jit.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/ClearTile.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/LoadTile.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/LoadTile_Linear.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/LoadTile_TileX.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/LoadTile_TileY.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_Linear2.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_Linear.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_TileW.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_TileX2.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_TileX.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_TileY2.cpp \
	$(MESA_VER)/src/gallium/drivers/swr/rasterizer/memory/StoreTile_TileY.cpp

MesaGdiLib_SRC = \
  $(MESA_VER)/src/gallium/winsys/sw/gdi/gdi_sw_winsys.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_buffer.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_clear.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_context.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_compute.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_draw_arrays.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_fence.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_flush.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_fs_exec.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_image.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_prim_vbuf.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_quad_blend.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_quad_depth_test.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_quad_fs.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_quad_pipe.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_quad_stipple.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_query.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_screen.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_setup.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_blend.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_clip.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_derived.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_image.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_rasterizer.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_sampler.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_shader.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_so.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_surface.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_state_vertex.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_surface.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_tex_sample.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_tex_tile_cache.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_texture.c \
  $(MESA_VER)/src/gallium/drivers/softpipe/sp_tile_cache.c \
  win9x/vramlock.c \
  win9x/vramcpy.c

MesaGdiLibGL_SRC = \
  $(MesaGdiLib_SRC) \
  $(MESA_VER)/src/gallium/targets/libgl-gdi/libgl_gdi.c
  
MesaGdiLibICD_SRC = \
  $(MesaGdiLib_SRC) \
  $(MESA_VER)/src/gallium/targets/libgl-gdi/libgl_gdi_icd.c
  
MesaGdiLibVMW_SRC = \
  $(MesaGdiLib_SRC) \
  win9x/libgl_vmws.c

MesaGalliumLLVMPipe_SRC += \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_alpha.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_blend.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_blend_aos.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_blend_logicop.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_depth.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_bld_interp.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_clear.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_context.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_draw_arrays.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_fence.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_flush.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_jit.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_memory.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_perf.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_query.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_rast.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_rast_debug.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_rast_tri.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_scene.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_scene_queue.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_screen.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_setup.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_setup_line.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_setup_point.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_setup_tri.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_setup_vbuf.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_blend.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_clip.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_derived.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_fs.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_gs.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_rasterizer.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_sampler.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_setup.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_so.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_surface.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_vertex.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_state_vs.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_surface.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_texture.c \
  $(MESA_VER)/src/gallium/drivers/llvmpipe/lp_tex_sample.c
